// Light theme colors
export const lightColors = {
  primary: "dimgrey",
  background: "whitesmoke",
  backgroundToolbar: "whitesmoke",
  backgroundNav: "whitesmoke",
  backgroundAvatar: "silver",
  backgroundSnipItem: "whitesmoke",
  backgroundYearGroup: "whitesmoke",
  borderSnip: "whitesmoke",
  borderYear: "lightgrey",
  text: "dimgrey",
  textAvatar: "whitesmoke",
  textGuide: "whitesmoke",
  textReadMore: "slategrey",
  textDate: "lightslategray",
  textSnipTitle: "grey",
  textSnipContent: "dimgrey",
  textYearGroup: "dimgrey",
  textVersion: "lightslategray",
  link: "#D3D3D3",
  linkerButton: "lightslategray",
  error: "slategrey",
};

// Dark theme colors
export const darkColors = {
  primary: "darkgrey",
  backgroundToolbar: "#101111",
  backgroundNav: "#101111",
  background: "#101111",
  backgroundAvatar: "dimgrey",
  backgroundSnipItem: "#101111",
  backgroundYearGroup: "#101111",
  borderSnip: "#101111",
  borderYear: "dimgrey",
  text: "gainsboro",
  textAvatar: "silver",
  textGuide: "whitesmoke",
  textReadMore: "slategrey",
  textDate: "lightslategray",
  textSnipTitle: "darkgray",
  textSnipContent: "dimgrey",
  textYearGroup: "darkgrey",
  textVersion: "lightslategray",
  link: "#D3D3D3",
  linkerButton: "lightslategray",
  error: "slategrey",
};
