import { Platform } from "react-native";
import Layout from "../constants/Layout";

// Light theme colors
export const lightColors = {
  primary: "dimgrey",
  background: "whitesmoke",
  backgroundToolbar: Layout.isSmallDevice ? "gainsboro" : "whitesmoke",
  backgroundNav: "whitesmoke",
  backgroundAvatar: "silver",
  backgroundSnipItem: "whitesmoke",
  backgroundYearGroup: "whitesmoke",
  backgroundClose: "lightgrey",
  borderSnip: "whitesmoke",
  borderYear: "lightgrey",
  text: "dimgrey",
  textAvatar: "whitesmoke",
  textGuide: "whitesmoke",
  textReadMore: "slategrey",
  textDate: "lightslategrey",
  textSnipHeader: "slategrey",
  textSnipTitle: "grey",
  textSnipContent: "dimgrey",
  textYearGroup: Layout.isSmallDevice ? "darkgrey" : "dimgrey",
  textSearchLabel: "slategrey",
  textSearchPlaceholder: "lightslategrey",
  textVersion: "lightslategrey",
  link: "#D3D3D3",
  linkerButton: "lightslategrey",
  backArrow: "slategrey",
  error: "slategrey",
};

// Dark theme colors
export const darkColors = {
  primary: "darkgrey",
  backgroundToolbar: Layout.isSmallDevice ? "black" : "#101111",
  backgroundNav: "#101111",
  background: "#101111",
  backgroundAvatar: "dimgrey",
  backgroundSnipItem: "#101111",
  backgroundYearGroup: "#101111",
  backgroundClose: "grey",
  borderSnip: "#101111",
  borderYear: "dimgrey",
  text: "gainsboro",
  textAvatar: "silver",
  textGuide: "whitesmoke",
  textReadMore: "slategrey",
  textDate: "lightslategrey",
  textSnipHeader: "slategrey",
  textSnipTitle: "darkgrey",
  textSnipContent: "dimgrey",
  textYearGroup: Layout.isSmallDevice ? "darkgrey" : "dimgrey",
  textSearchLabel: "slategrey",
  textSearchPlaceholder: "lightslategrey",
  textVersion: "lightslategrey",
  link: "#D3D3D3",
  linkerButton: "lightslategrey",
  backArrow: "slategrey",
  error: "slategrey",
};
